//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Action
    {
        public int IdAction { get; set; }
        public System.DateTime ActionDate { get; set; }
        public string Login { get; set; }
        public int IdActionType { get; set; }
        public int IdWorkingTable { get; set; }
        public Nullable<int> IdAffectedElement { get; set; }
    
        public virtual ActionType ActionType { get; set; }
        public virtual WorkingTable WorkingTable { get; set; }

        public string FormatedDate
        {
            get
            {
                string formattedDate = ActionDate.ToString("dd.MM.yy HH:mm:ss");
                return formattedDate;
            }
        }

        public string ActionName
        {
            get
            {
                string name = "";

                switch (IdActionType)
                {
                    case 1:
                        name = "Добавление записи";
                        break;
                    case 2:
                        name = "Редактирование записи";
                        break;
                    case 3:
                        name = "Удаление записи";
                        break;
                }

                return name;
            }
        }

        public string WorkingTableName
        {
            get
            {
                string name = "";

                switch (IdWorkingTable)
                {
                    case 1:
                        name = "Налогоплательщики";
                        break;
                    case 2:
                        name = "Собственность";
                        break;
                    case 3:
                        name = "Налоговые ставки";
                        break;
                    case 4:
                        name = "Сотрудники";
                        break;
                }

                return name;
            }
        }
    }
}
