//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Employee()
        {
            this.Payment = new HashSet<Payment>();
        }
    
        public int IdEmployee { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Patronymic { get; set; }
        public bool Gender { get; set; }
        public int Phone { get; set; }
        public System.DateTime StartDate { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }

        public string FIO
        {
            get
            {
                return $"{LName} {FName} {Patronymic}";
            }
        }

        public string GenderName
        {
            get
            {
                string name = "";

                if (Gender == true)
                {
                    name = "Мужской";
                }
                else
                {
                    name = "Женский";
                }

                return name;
            }
        }

        public string FormatedDate
        {
            get
            {
                string formattedDate = StartDate.ToString("dd.MM.yy HH:mm:ss");
                return formattedDate;
            }
        }
    }
}
