//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Logs
    {
        public int IdLogin { get; set; }
        public int IdUserType { get; set; }
        public System.DateTime LoginDate { get; set; }
        public string Login { get; set; }
    
        public virtual UserType UserType { get; set; }

        public string FormatedDate
        {
            get
            {
                string formattedDate = LoginDate.ToString("dd.MM.yy HH:mm:ss");
                return formattedDate;
            }
        }

        public string UserName
        {
            get
            {
                string name = "";

                switch (IdUserType)
                {
                    case 1:
                        name = "Администратор";
                        break;
                    case 2:
                        name = "Налоговый инспектор";
                        break;
                    case 3:
                        name = "Налогоплательщик";
                        break;
                }

                return name;
            }
        }
    }
}
