//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Payment
    {
        public int IdPayment { get; set; }
        public int IdTaxpayer { get; set; }
        public Nullable<int> IdArrears { get; set; }
        public Nullable<int> IdTax { get; set; }
        public int IdEmployee { get; set; }
        public bool TypeOfPayment { get; set; }
        public decimal Sum { get; set; }
        public System.DateTime DateOfPayment { get; set; }
    
        public virtual Arrears Arrears { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual Tax Tax { get; set; }

        public string FormatedDate
        {
            get
            {
                string formattedDate = DateOfPayment.ToString("dd.MM.yy HH:mm:ss");
                return formattedDate;
            }
        }

        public string TaxpayerName
        {
            get
            {
                if (IdArrears != null)
                {
                    return Arrears.TaxpayerName;
                }
                else
                {
                    return Tax.TaxpayerName;
                }
            }
        }

        public string EmployeeName
        {
            get
            {
                return Employee.FIO;
            }
        }

        public string SumRub
        {
            get
            {
                string sum = Sum.ToString("N2");
                return sum;
            }
        }

        public string TypeOfPaymentName
        {
            get
            {
                string name = "";

                if (TypeOfPayment == true)
                {
                    name = "По задолженности";
                }
                else
                {
                    name = "По налогу";
                }

                return name;
            }
        }
    }
}
