//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Property
    {
        public int IdProperty { get; set; }
        public int IdTaxpayer { get; set; }
        public int IdTypeOfProperty { get; set; }
        public string Description { get; set; }
        public System.DateTime DateOfPurchase { get; set; }
        public decimal Sum { get; set; }
        public byte[] Image { get; set; }
    
        public virtual Taxpayer Taxpayer { get; set; }
        public virtual TypeOfProperty TypeOfProperty { get; set; }

        public string FormatedDate
        {
            get
            {
                string formattedDate = DateOfPurchase.ToString("dd.MM.yy HH:mm:ss");
                return formattedDate;
            }
        }

        public string TypeOfPropertyName
        {
            get
            {
                string name = "";

                switch (IdTypeOfProperty)
                {
                    case 1:
                        name = "Движимая собственность";
                        break;
                    case 2:
                        name = "Недвижимая собственность";
                        break;
                }

                return name;
            }
        }

        public string SumRub
        {
            get
            {
                string sum = Sum.ToString("N2");
                return sum;
            }
        }

        public string TaxpayerName
        {
            get
            {
                return Taxpayer.FIO;
            }
        }
    }
}
