//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tax
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tax()
        {
            this.Arrears = new HashSet<Arrears>();
            this.Payment = new HashSet<Payment>();
        }
    
        public int IdTax { get; set; }
        public int IdTaxpayer { get; set; }
        public int IdTaxRate { get; set; }
        public decimal Sum { get; set; }
        public System.DateTime PaymentDeadline { get; set; }
        public bool Status { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arrears> Arrears { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Payment> Payment { get; set; }
        public virtual Taxpayer Taxpayer { get; set; }
        public virtual TaxRate TaxRate { get; set; }

        public string FormatedDate
        {
            get
            {
                string formattedDate = PaymentDeadline.ToString("dd.MM.yy HH:mm:ss");
                return formattedDate;
            }
        }

        public string SumRub
        {
            get
            {
                string sum = Sum.ToString("N2");
                return sum;
            }
        }

        public string StatusName
        {
            get
            {
                string name = "";

                if (Status == true)
                {
                    name = "Оплачен";
                }
                else
                {
                    name = "Не оплачен";
                }

                return name;
            }
        }

        public string Percent
        {
            get
            {
                return $"{TaxRate.Percent}%";
            }
        }

        public string TaxpayerName
        {
            get
            {
                return Taxpayer.FIO;
            }
        }
    }
}
