//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLink
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TaxInspectionEntities1 : DbContext
    {
        public TaxInspectionEntities1()
            : base("name=TaxInspectionEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Action> Action { get; set; }
        public virtual DbSet<ActionType> ActionType { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Arrears> Arrears { get; set; }
        public virtual DbSet<Citizenship> Citizenship { get; set; }
        public virtual DbSet<CitizenshipTaxpayer> CitizenshipTaxpayer { get; set; }
        public virtual DbSet<Employee> Employee { get; set; }
        public virtual DbSet<Logs> Logs { get; set; }
        public virtual DbSet<Payment> Payment { get; set; }
        public virtual DbSet<Property> Property { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Tax> Tax { get; set; }
        public virtual DbSet<Taxpayer> Taxpayer { get; set; }
        public virtual DbSet<TaxRate> TaxRate { get; set; }
        public virtual DbSet<TypeOfProperty> TypeOfProperty { get; set; }
        public virtual DbSet<UpdateTax> UpdateTax { get; set; }
        public virtual DbSet<UserType> UserType { get; set; }
        public virtual DbSet<WorkingTable> WorkingTable { get; set; }
    }
}
