//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class Taxpayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Taxpayer()
        {
            this.CitizenshipTaxpayer = new HashSet<CitizenshipTaxpayer>();
            this.Property = new HashSet<Property>();
            this.Tax = new HashSet<Tax>();
        }
    
        public int IdTaxpayer { get; set; }
        public string FName { get; set; }
        public string LName { get; set; }
        public string Patronymic { get; set; }
        public string INN { get; set; }
        public bool Gender { get; set; }
        public string Phone { get; set; }
        public string BirthPlace { get; set; }
        public string PassportSeries { get; set; }
        public string PassportNumber { get; set; }
        public string Address { get; set; }
        public string Login { get; set; }
        public string Password { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CitizenshipTaxpayer> CitizenshipTaxpayer { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Property> Property { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax> Tax { get; set; }

        public string FIO
        {
            get
            {
                return $"{LName} {FName} {Patronymic}";
            }
        }

        public string PassportFull
        {
            get
            {
                return $"{PassportSeries} {PassportNumber}";
            }
        }

        public string GenderName
        {
            get
            {
                string name = "";

                if (Gender == true)
                {
                    name = "Мужской";
                }
                else
                {
                    name = "Женский";
                }

                return name;
            }
        }
    }
}
