//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class TaxRate
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public TaxRate()
        {
            this.Tax = new HashSet<Tax>();
        }
    
        public int IdTaxRate { get; set; }
        public double PercentRate { get; set; }
        public System.DateTime StartDate { get; set; }
        public Nullable<System.DateTime> FinishDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tax> Tax { get; set; }

        public string FormatedStartDate
        {
            get
            {
                string formattedDate = StartDate.ToString("dd.MM.yy HH:mm:ss");
                return formattedDate;
            }
        }

        public string Percent
        {
            get
            {
                double percent = PercentRate * 10;
                return $"{percent}";
            }
        }

        public string FormatedFinishDate
        {
            get
            {
                string formattedDate = "";
                if (FinishDate.HasValue)
                {
                    formattedDate = FinishDate.Value.ToString("dd.MM.yy HH:mm:ss");
                }

                return formattedDate;
            }
        }
    }
}
