//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TaxLink
{
    using System;
    using System.Collections.Generic;
    
    public partial class UpdateTax
    {
        public int IdUpdateTax { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public System.DateTime NextUpdateDate { get; set; }
    }
}
